api_login_check:
    path: /api/login_check
    methods:  [POST]

register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: [POST]

categories:
    path: /api/categories
    controller: App\Controller\CategoriesController::index
    methods: [GET, POST, PUT, DELETE]