api_login_check:
    path: /api/user/login_check
    methods:  [POST]


controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        prefix: api/
    type: attribute