api_login_check:
    path: /api/login_check
    methods:  [POST]

register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: [POST]

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        prefix: api/
    type: attribute